[build]
builder = "nixpacks"
buildCommand = "echo 'No build needed, serving static files'"

[deploy]
startCommand = "npx serve dist"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 